version: '2'

services:
#MySQL Container
  mysql:
# Downloads latest MySQL image from Docker Hub
    image: mysql:latest
# Network if you have created one for your containers if not leave commented out
#    networks:
#      - valterseu
# Always restart the container on failure or when VPS/Server is restarted auto start docker container
    restart: always
# Additional commands for Native password and encoding to support all the characters
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
# Mount MySQL directory that contains DB files with your linux folder.
    volumes:
      - /srv/docker/mysql:/var/lib/mysql
# MySQL root main admin password please choose a strong password, don't use this demo password!
    environment:
      - MYSQL_ROOT_PASSWORD=ThisIsADemoPasswordNot@Real12454

# TeamPass Docker container
  teampass:
# Downloads latest MySQL image from Docker Hub
    image: valterseu/teampass
# Network if you have created one for your containers if not leave commented out
#    networks:
#      - valterseu
# Always restart the container on failure or when VPS/Server is restarted auto start docker container
    restart: always
# Change mysubdomain.domain.com to your domain or subdomain
    command: --hostname=mysubdomain.domain.com
    ports:
      - 829:80
      - 429:443
# Links mean that the TeamPass container is dependent on the MySQL container, if the MySQL container doesn't work, then TeamPass will also not start
    links:
      - mysql
# Replace the domain name from mysubdomain.domain.com with your domain or subdomain and also replace somemail@somedomainmail.com with your e-mail where Let's encrypt if you are using # it to send information reminders about certificate expiration
    environment:
      - VIRTUAL_HOST=mysubdomain.domain.com
      - LETSENCRYPT_EMAIL=somemail@somedomainmail.com
      - LETSENCRYPT_HOST=mysubdomain.domain.com

#Network if you have created one for your containers if not leave commented out
#networks:
#  valterseu:
#    external: true
